{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "89108370",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "3423"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import json\n",
    "from pathlib import Path\n",
    "\n",
    "URL = \"https://subastas.boe.es/subastas_ava.php\"\n",
    "SEEN_FILE = Path(\"subastas_madrid_vistas.json\")\n",
    "TOPIC = \"subastas-madrid-vivienda-350k\"\n",
    "\n",
    "data = {\n",
    "    \"campo[0]\": \"SUBASTA.ORIGEN\", \"dato[0]\": \"\",\n",
    "    \"campo[1]\": \"SUBASTA.AUTORIDAD\", \"dato[1]\": \"\",\n",
    "    \"campo[2]\": \"SUBASTA.ESTADO.CODIGO\", \"dato[2]\": \"PU\",\n",
    "    \"campo[3]\": \"BIEN.TIPO\", \"dato[3]\": \"I\",\n",
    "    \"dato[4]\": \"501\",\n",
    "    \"campo[5]\": \"BIEN.DIRECCION\", \"dato[5]\": \"\",\n",
    "    \"campo[6]\": \"BIEN.CODPOSTAL\", \"dato[6]\": \"\",\n",
    "    \"campo[7]\": \"BIEN.LOCALIDAD\", \"dato[7]\": \"Madrid\",\n",
    "    \"campo[8]\": \"BIEN.COD_PROVINCIA\", \"dato[8]\": \"28\",\n",
    "    \"campo[9]\": \"SUBASTA.POSTURA_MINIMA_MINIMA_LOTES\",\n",
    "    \"dato[9]\": \"35000000\",\n",
    "    \"page_hits\": \"50\",\n",
    "    \"sort_field[0]\": \"SUBASTA.FECHA_FIN\",\n",
    "    \"sort_order[0]\": \"asc\",\n",
    "    \"accion\": \"Buscar\"\n",
    "}\n",
    "\n",
    "def notify(msg):\n",
    "    requests.post(\n",
    "        f\"https://ntfy.sh/{TOPIC}\",\n",
    "        data=msg.encode(\"utf-8\"),\n",
    "        headers={\"Title\": \"Nueva vivienda BOE Madrid\"}\n",
    "    )\n",
    "\n",
    "seen = set(json.loads(SEEN_FILE.read_text())) if SEEN_FILE.exists() else set()\n",
    "\n",
    "r = requests.post(URL, data=data, timeout=20)\n",
    "soup = BeautifulSoup(r.text, \"html.parser\")\n",
    "\n",
    "for a in soup.select(\"a[href*='subasta.php'], a[href*='idSub=']\"):\n",
    "    link = \"https://subastas.boe.es/\" + a[\"href\"].lstrip(\"./\")\n",
    "    title = a.get_text(\" \", strip=True)\n",
    "\n",
    "    if \"SUB-\" in title and link not in seen:\n",
    "        notify(f\"{title}\\n{link}\")\n",
    "        seen.add(link)\n",
    "\n",
    "SEEN_FILE.write_text(json.dumps(list(seen), indent=2))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "06290536",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Subastas encontradas: 5\n",
      "Nuevas notificadas: 5\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "from pathlib import Path\n",
    "import json\n",
    "import re\n",
    "from urllib.parse import urljoin\n",
    "\n",
    "URL = \"https://subastas.boe.es/subastas_ava.php\"\n",
    "BASE = \"https://subastas.boe.es/\"\n",
    "\n",
    "# CAMBIA ESTO por el mismo topic que pongas en la app ntfy\n",
    "NTFY_TOPIC = \"subastas-madrid-vivienda-jorge-350k\"\n",
    "\n",
    "SEEN_FILE = Path(\"subastas_vistas_2.json\")\n",
    "\n",
    "DATA = {\n",
    "    \"campo[0]\": \"SUBASTA.ORIGEN\",\n",
    "    \"dato[0]\": \"\",\n",
    "\n",
    "    \"campo[1]\": \"SUBASTA.AUTORIDAD\",\n",
    "    \"dato[1]\": \"\",\n",
    "\n",
    "    \"campo[2]\": \"SUBASTA.ESTADO.CODIGO\",\n",
    "    \"dato[2]\": \"PU\",  # Próxima apertura\n",
    "\n",
    "    \"campo[3]\": \"BIEN.TIPO\",\n",
    "    \"dato[3]\": \"I\",  # Inmuebles\n",
    "\n",
    "    \"campo[4]\": \"BIEN.SUBTIPO\",\n",
    "    \"dato[4]\": \"501\",  # Vivienda\n",
    "\n",
    "    \"campo[5]\": \"BIEN.DIRECCION\",\n",
    "    \"dato[5]\": \"\",\n",
    "\n",
    "    \"campo[6]\": \"BIEN.CODPOSTAL\",\n",
    "    \"dato[6]\": \"\",\n",
    "\n",
    "    \"campo[7]\": \"BIEN.LOCALIDAD\",\n",
    "    \"dato[7]\": \"Madrid\",\n",
    "\n",
    "    \"campo[8]\": \"BIEN.COD_PROVINCIA\",\n",
    "    \"dato[8]\": \"28\",  # Madrid\n",
    "\n",
    "    \"campo[9]\": \"SUBASTA.POSTURA_MINIMA_MINIMA_LOTES\",\n",
    "    \"dato[9]\": \"35000000\",  # 350.000 € en céntimos\n",
    "\n",
    "    \"campo[10]\": \"SUBASTA.NUM_CUENTA_EXPEDIENTE_1\",\n",
    "    \"dato[10]\": \"\",\n",
    "\n",
    "    \"campo[11]\": \"SUBASTA.NUM_CUENTA_EXPEDIENTE_2\",\n",
    "    \"dato[11]\": \"\",\n",
    "\n",
    "    \"campo[12]\": \"SUBASTA.NUM_CUENTA_EXPEDIENTE_3\",\n",
    "    \"dato[12]\": \"\",\n",
    "\n",
    "    \"campo[13]\": \"SUBASTA.NUM_CUENTA_EXPEDIENTE_4\",\n",
    "    \"dato[13]\": \"\",\n",
    "\n",
    "    \"campo[14]\": \"SUBASTA.NUM_CUENTA_EXPEDIENTE_5\",\n",
    "    \"dato[14]\": \"\",\n",
    "\n",
    "    \"campo[15]\": \"SUBASTA.ID_SUBASTA_BUSCAR\",\n",
    "    \"dato[15]\": \"\",\n",
    "\n",
    "    \"campo[16]\": \"SUBASTA.ACREEDORES\",\n",
    "    \"dato[16]\": \"\",\n",
    "\n",
    "    \"campo[17]\": \"SUBASTA.FECHA_FIN\",\n",
    "    \"dato[17][0]\": \"\",\n",
    "    \"dato[17][1]\": \"\",\n",
    "\n",
    "    \"campo[18]\": \"SUBASTA.FECHA_INICIO\",\n",
    "    \"dato[18][0]\": \"\",\n",
    "    \"dato[18][1]\": \"\",\n",
    "\n",
    "    \"page_hits\": \"50\",\n",
    "    \"sort_field[0]\": \"SUBASTA.FECHA_FIN\",\n",
    "    \"sort_order[0]\": \"asc\",\n",
    "    \"accion\": \"Buscar\",\n",
    "}\n",
    "\n",
    "\n",
    "def cargar_vistas():\n",
    "    if SEEN_FILE.exists():\n",
    "        return set(json.loads(SEEN_FILE.read_text(encoding=\"utf-8\")))\n",
    "    return set()\n",
    "\n",
    "\n",
    "def guardar_vistas(vistas):\n",
    "    SEEN_FILE.write_text(\n",
    "        json.dumps(sorted(list(vistas)), indent=2, ensure_ascii=False),\n",
    "        encoding=\"utf-8\"\n",
    "    )\n",
    "\n",
    "\n",
    "def notificar(mensaje):\n",
    "    url = f\"https://ntfy.sh/{NTFY_TOPIC}\"\n",
    "    requests.post(\n",
    "        url,\n",
    "        data=mensaje.encode(\"utf-8\"),\n",
    "        headers={\n",
    "            \"Title\": \"Nueva subasta vivienda Madrid\",\n",
    "            \"Priority\": \"high\",\n",
    "            \"Tags\": \"house,warning\"\n",
    "        },\n",
    "        timeout=20\n",
    "    )\n",
    "\n",
    "\n",
    "def buscar_subastas():\n",
    "    r = requests.post(URL, data=DATA, timeout=30)\n",
    "    r.raise_for_status()\n",
    "\n",
    "    soup = BeautifulSoup(r.text, \"html.parser\")\n",
    "\n",
    "    subastas = {}\n",
    "\n",
    "    for a in soup.find_all(\"a\", href=True):\n",
    "        href = a[\"href\"]\n",
    "\n",
    "        if \"detalleSubasta.php?idSub=\" not in href:\n",
    "            continue\n",
    "\n",
    "        match = re.search(r\"idSub=([^&]+)\", href)\n",
    "        if not match:\n",
    "            continue\n",
    "\n",
    "        id_subasta = match.group(1)\n",
    "        link = urljoin(BASE, href)\n",
    "\n",
    "        subastas[id_subasta] = link\n",
    "\n",
    "    return subastas\n",
    "\n",
    "\n",
    "def main():\n",
    "    vistas = cargar_vistas()\n",
    "    subastas = buscar_subastas()\n",
    "\n",
    "    nuevas = 0\n",
    "\n",
    "    for id_subasta, link in subastas.items():\n",
    "        if id_subasta not in vistas:\n",
    "            mensaje = (\n",
    "                f\"Nueva subasta de vivienda en Madrid\\n\\n\"\n",
    "                f\"{id_subasta}\\n\"\n",
    "                f\"Postura mínima inferior a 350.000 €\\n\\n\"\n",
    "                f\"{link}\"\n",
    "            )\n",
    "\n",
    "            notificar(mensaje)\n",
    "            vistas.add(id_subasta)\n",
    "            nuevas += 1\n",
    "\n",
    "    guardar_vistas(vistas)\n",
    "\n",
    "    print(f\"Subastas encontradas: {len(subastas)}\")\n",
    "    print(f\"Nuevas notificadas: {nuevas}\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
